language:
    - cpp

# compiler:
#     - gcc
#     - clang


env:
    - BUILD=g++
    - BUILD=clang++
#   - BUILD=Emscripten

# CXX and CC environment variables are always reset by travis after env section is executed. Don't set them here

before_install:
    # Add software package repositories with recent versions of gcc and boost
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test --yes
    - sudo add-apt-repository ppa:boost-latest/ppa --yes
    - sudo apt-get update -qq
    # Install GNU GCC 4.8 required by use of C++11
    - if [ "$BUILD" = "g++" ] || [ "$BUILD" = "Emscripten" ]; then sudo apt-get install -qq g++-4.8 && export CXX="g++-4.8" CC="gcc-4.8";  fi
    - if [ "$BUILD" = "clang++" ]; then sudo apt-get install libstdc++-4.8-dev && export CXX="clang++" CC="clang"; fi

install:
    # Install mfast dependencies
    - sudo apt-get install -qq libboost1.55
    # - sudo apt-get install libboost1.53-dev ibboost-filesystem1.53-dev libboost-system1.53-dev libboost-test1.53-dev

script:
    # - if [ $BUILD == Emscripten ]; then ./travis-install-emscripten.sh && cd emsdk_portable && source ./emsdk_env.sh && cd ..; fi
    - mkdir _builds
    - cd _builds
    - cmake ..
    - make
    - make test
# whitelist
branches:
  only:
    - master